### ISSUE TITLE
Yahoo SMTP check returns true for any input

### ISSUE THREAD

**Issue by razvanioan** [apilayer/mailboxlayer-API#1]
Hi there,

Great service, but I've seen that at least for Yahoo SMTP check it always returns true, which is not correct.

Regards,

**Comment by apilayer** [comment]
Hello, 

Thank you for reaching out and submitting this issue. We will look into this and get back to you in the shortest time possible. 

For further questions please refer to our customer support service at [support@apilayer.com](mailto:support@apilayer.com). 

Best regards, 
apilayer Support
